### ISSUE TITLE
Renderer Issue on MacOS

### ISSUE THREAD

**Issue by DOCS-kdu3** [sketchpunk/Fungi#2]
Hi,

I recently grown interest in learning Web GL2 and have stumbled upon your work. It is a fantastic resource. I started opening your lessons at random, and have discovered that every lesson since Lesson 77 will not render on my machine in both Chrome and Firefox. It seems to always be a problem with the Vao or Renderer class.

Chrome Error:
Lesson 77:
```
[.WebGL-0x7f90c6800800]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: uniform buffers : buffer or buffer range at index 0 not large enough
[.WebGL-0x7f90c6800800]GL ERROR :GL_INVALID_OPERATION : glDrawElements: uniform buffers : buffer or buffer range at index 0 not large enough
```

Chrome Error:
Lesson 125:
```
[.WebGL-0x7fd971064600]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: uniform buffers : buffer or buffer range at index 0 not large enough
[.WebGL-0x7fd971064600]GL ERROR :GL_INVALID_OPERATION : glDrawElements: uniform buffers : buffer or buffer range at index 0 not large enough
[.WebGL-0x7fd971064600]GL ERROR :GL_INVALID_OPERATION : glDrawElementsInstancedANGLE: uniform buffers : buffer or buffer range at index 0 not large enough
```

Firefox Error:
Lesson 77:
```
Error: WebGL warning: drawArrays: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE. Renderable.js:51:19
Error: WebGL warning: drawElements: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE. Renderable.js:50:33
```

Firefox Error:
Lesson 125:
```
Error: WebGL warning: drawArrays: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE. Renderer.js:140:20
Error: WebGL warning: drawElements: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE. Renderer.js:139:32
```

If there is more information I could provide you, please let me know.

**Comment by DOCS-kdu3** [comment]
Lesson 85 
line_effects.html 

does render properly on my machine.

**Comment by sketchpunk** [comment]
I kind of know of the issue but it seems to be only on macs. I dont have access to a mac to try to debug and fix this issue. It might have something to do with UBOs and Metal, WebGL is converted to Metal on macs, DirectX on PC, and I believe OpenGL on linux.

Since i can not replicate this error on the PC, not much I can do. I dont know if there is some weird ubo rule on metal that I dont know, like vec3+float != float+vec3... OR maybe on metal they are equal. 

All i can see is the UBO being created on the GPU is smaller then what I calculated it to be. So my binary array is to big to fit into the gpu buffer.

**Comment by DOCS-kdu3** [comment]
Hi,

Thanks for the insight. I was able to view lesson 125 doing the following:
https://github.com/sketchpunk/Fungi/blob/af196711cae945275408f6bb604e5471c97d1f12/fungi/core/Ubo.js#L142-L143

I deleted line 142 and changed the `else if` to an `if` on line 143



I think I may be missing the material on the model now though, not sure if that is related or a separate issue.
![image](https://user-images.githubusercontent.com/40775057/60600577-648e5380-9d7e-11e9-9316-bb5ce199cf8b.png)

**Comment by DOCS-kdu3** [comment]
I was able to get some color. I subtracted 4 from the offset in the if statement. The color is a different color than the one in your video so still unsure if this is correct.
```
if(blockSpace > 0 && prevItem && !(blockSpace == 16 && size[1] >= 16) ){
	prevItem.blockSize += blockSpace;
	offset 		+= blockSpace - 4;
	blockSpace	= 16 - size[1];
}
```

![image](https://user-images.githubusercontent.com/40775057/60604359-8808cc80-9d85-11e9-9acd-667c0ca3584b.png)

**Comment by sketchpunk** [comment]
Dont think the change you did is fixing the underlining problem. The way I tested this in the past was I created a test shader with a custom UBO, then I ask webgl how large in bytes is it. Then I can compare that to what I've calculated. If WebGL gives you a different number then how I've calculated it then there must be something specific about the ubo layout that might have some sort of exception or a miscalculation on my part somewhere when figuring out offsets, chunk sizes and total buffer size.

Thats how I learned that Vec3+Float != Float+Vec3.  When I did Float+Vec3, webgl gave me back a value of 32 bytes which makes no sense when its just 16 bytes of data. After digging, thats when I found the exception that vec3 must always be the starting point of a 16byte chunk. So starting a chunk with a float, violates that rule which causes the GPU to pad the remaining chunk and create a new one to contain the vec3, resulting in 16 bytes of data being stored in 32 byte buffer, with 12 bytes of wasted space between the two values.

**Comment by sketchpunk** [comment]
Looking at the UBO code and saw some test functions in there. One function outputs the max block size. That might also be a possibility, Not sure which UBO is causing the problem but the one for armature bones is pretty big, so maybe its hitting the max limit related to your graphics card or metal's limit. If its that UBO causing the problem, then that might be the issue.

https://github.com/sketchpunk/Fungi/blob/af196711cae945275408f6bb604e5471c97d1f12/fungi/core/Ubo.js#L190

**Comment by DOCS-kdu3** [comment]
I apologize for not really being up to speed on this project - I've only just started looking at it very recently. What would be the best way to call that function? 

Presently I tried importing Ubo.js into Renderer and modifying the loadShader method as so:
```
loadShader( s ){
  if( this.shader !== s ){
    this.shader = s;

    let val =  s.uniforms.values().next().value;

    if(val)
      Ubo.testShader(s, val);

    gl.ctx.useProgram( s.program );
  }
  return this;
}
```

That method is not yield any useful data:
```
======================================TEST SHADER
Ubo.js:197 BlockIndex : 4294967295
Ubo.js:200 Data Size : NaN
Ubo.js:203 Indice  null
Ubo.js:206 Uniforms : NaN
Ubo.js:209 Uniform Block Binding :  null
```

**Comment by sketchpunk** [comment]
https://github.com/sketchpunk/Fungi/blob/master/fungi.tools/ubo_tester.html
I posted a file that will take a UBO that you generate, create a tmp shader that uses it then feeds back all the info I can get from webgl related to the UBO in the shader. Its order placement, offset, and type is important. In the code I have all  the UBOs that I have in fungi. Just uncomment each one and see if the data given back shows that both the calculated version matches up with what the shader reports.

like
`############################################
VALIDATOR
ubo_tester.html:121 UBO Generated code :  uniform ubo_test{ mat4 projViewMatrix; vec3 cameraPos; float globalTime; vec2 screenSize;  }; 
ubo_tester.html:133 -- Calc Buf Size: 88 >> Shader Buf Size: 88
ubo_tester.html:136 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ubo_tester.html:137 Item 0 : projViewMatrix
ubo_tester.html:138 -- Calc Offset: 0 >> Shader Offset: 0
ubo_tester.html:139 -- Calc Type: mat4 >> Shader Type: FLOAT_MAT4`

**Comment by DOCS-kdu3** [comment]
Hi,

I believe I figured out a proper solution to the problem.

Here are some initial logs using the original source code and utilizing the new ubo_tester.html
[FloatAndVec3.log](https://github.com/sketchpunk/Fungi/files/3369347/FloatAndVec3.log)
[UboGlobal.log](https://github.com/sketchpunk/Fungi/files/3369349/UboGlobal.log)
[Both.log](https://github.com/sketchpunk/Fungi/files/3369353/Both.log)

The Offset was always correct, but the sizing was always 4 bytes off per vec3 uniform.

My original working solution was the following:
In Ubo.js 
```
static finalize( ubo, bindPoint ){
	// Finish Setting up UBO
	ubo.bufferSize	= Ubo.calculate( ubo.items );			// Calc all the Offsets and Lengths
	ubo.bufferID 	= gl.ctx.createBuffer();				// Create Standard Buffer
	while(ubo.bufferSize % 16 != 0)
        	ubo.bufferSize += 4;
	ubo.byteBuffer	= new ByteBuffer( ubo.bufferSize );
	...
```



Finally, I moved the math to the calculate method. After the for loop:
```
while(offset % 16 != 0)
	offset += 4;
```
This change yields these logs:
[FloatVecWChanges.log](https://github.com/sketchpunk/Fungi/files/3369361/FloatVecWChanges.log)
[UboGlobalWChanges.log](https://github.com/sketchpunk/Fungi/files/3369363/UboGlobalWChanges.log)
[BothWChanges.log](https://github.com/sketchpunk/Fungi/files/3369366/BothWChanges.log)

and I am able to render Vegeta with the proper color.

**Comment by DOCS-kdu3** [comment]
[FinalLogAllUbos.log](https://github.com/sketchpunk/Fungi/files/3369564/FinalLogAllUbos.log)

I also tested out the lower bounds of a single int and vec2 incase the 16 byte minimum was too small. They seem to check out properly.

```
VALIDATOR
UBO Generated code :  uniform ubo_test{ int var01;  }; 
Calc Buf Size: 16 >> Shader Buf Size: 16
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Item 0 : var01
Calc Offset: 0 >> Shader Offset: 0
Calc Type: int >> Shader Type: INT

----
VALIDATOR
UBO Generated code :  uniform ubo_test{ vec2 var01;  }; 
Calc Buf Size: 16 >> Shader Buf Size: 16
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Item 0 : var01
Calc Offset: 0 >> Shader Offset: 0
Calc Type: vec2 >> Shader Type: FLOAT_VEC2

```

**Comment by sketchpunk** [comment]
So the only thing you seem to be doing is to change the final offset value that is used as the total buffer size if I understand what you did. So that the final byte size for the buffer is equal when calculated and when checking it from the shader.

Ok... I think I finally understand the problem. Long Long time ago, In the first version of UBO, I padded the final chunk, so that each 16 byte chunk is accounted for. At some point I noticed that I dont need to pad the remaining bytes which things will still work for me. So why waste extra bytes when its not needed. BUT if padding the final 16 byte chunk is what fixes the issue, then I'm assuming the Mac Implementation of WebGL's UBO feature requires that the byte buffer size that I'm using to pass data to the gpu MUST equal that of what the GPU calculates the size to be itself.

So on the PC, I can dump less bytes then the total on the gpu, but on the mac the bytes must be equal. Putting the padding in shouldn't break windows since it did work originally that way. 

Sweet. Thanks for being the mac guy on this. So totally my fault for taking away the padding. Never thought that would of been an issue.

Instead of using a loop, how about we calculate the offset. Try something like this 
let padding = offset % 16;
if( padding != 0 ) offset += 16 - padding;

So if offset = 18, then 18 % 16 = 2.  So we have two bytes over, so we need to pad it by 14 more bytes. Since we know the entire chunk needs to be 16 bytes, we can just say 16 - padding + offset to get our final buffer size with all 16 byte chunks filled and accounted for.

**Comment by DOCS-kdu3** [comment]
Just tried it out and it all works. 

A padding variable definitely is more expressive.

I've just submitted a commit on my personal github account rather than this work one. I work in academia and have had the opportunity to investigate some topics interesting to myself between projects. I'm pretty busy recently but if I do graphics in the future it'll be on my own time - occasionally I try to learn on break.
